# Do not trigger builds on commits and merges to branch
trigger: none

# Trigger builds on PRs
pr:
  branches:
    include:
    - main
  paths:
    include:
      - Deployments/Resource_group

extends:
  template: ../../Shared/azure-pipelines.yml