stages:
- stage: Unit
  condition: or(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual')
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  
  - job: Test
    displayName: 'Test'
    continueOnError: false
    steps:

    # Bootstrap steps
    - template: ../Steps/bootstrap.yml
    
    # Test specific step
    - template: ../Steps/go.yml
      parameters:
        arguments: '-v unit_test.go'